// Canonical default content. Used by /api/content and the admin editor as the
// seed/fallback whenever the database has no override for a collection.
const dealers = [
  { id: 'publicGold', name: 'Public Gold', cat: 'dealer', type: 'physical', pop: 1, en: 'Largest private gold dealer', bm: 'Peniaga emas swasta terbesar', url: 'https://publicgold.com.my', buy: { 999: 1.12, 916: 1.15, 750: 1.18 }, sell: { 999: 0.98, 916: 0.97, 750: 0.96 } },
  { id: 'pohKong', name: 'Poh Kong', cat: 'jeweller', type: 'physical', pop: 2, en: 'Bursa-listed jewellery chain', bm: 'Rangkaian barang kemas tersenarai Bursa', url: 'https://pohkong.com.my', buy: { 999: 1.09, 916: 1.13, 750: 1.16 }, sell: { 999: 0.97, 916: 0.96, 750: 0.95 } },
  { id: 'habib', name: 'Habib Jewels', cat: 'jeweller', type: 'physical', pop: 3, en: 'Premium jewellery retailer', bm: 'Peruncit barang kemas premium', url: 'https://habib.my', buy: { 999: 1.10, 916: 1.14, 750: 1.17 }, sell: { 999: 0.97, 916: 0.95, 750: 0.94 } },
  { id: 'tomei', name: 'Tomei', cat: 'jeweller', type: 'physical', pop: 6, en: 'Bursa-listed gold & jewellery', bm: 'Emas & barang kemas tersenarai Bursa', url: 'https://tomei.com.my', buy: { 999: 1.09, 916: 1.12, 750: 1.15 }, sell: { 999: 0.97, 916: 0.96, 750: 0.95 } },
  { id: 'wahChan', name: 'Wah Chan', cat: 'jeweller', type: 'physical', pop: 8, en: 'Established gold retailer', bm: 'Peruncit emas lama bertapak', url: 'https://wahchan.com.my', buy: { 999: 1.09, 916: 1.13, 750: 1.16 }, sell: { 999: 0.97, 916: 0.95, 750: 0.94 } },
  { id: 'zhulian', name: 'Zhulian', cat: 'jeweller', type: 'physical', pop: 10, en: 'Direct-selling jeweller', bm: 'Barang kemas jualan langsung', url: 'https://zhulian.com.my', buy: { 999: 1.10, 916: 1.14, 750: 1.17 }, sell: { 999: 0.96, 916: 0.95, 750: 0.94 } },
  { id: 'helloGold', name: 'HelloGold', cat: 'digital', type: 'digital', pop: 5, en: 'Digital gold savings app', bm: 'Aplikasi simpanan emas digital', url: 'https://hellogold.com', buy: { 999: 1.03 }, sell: { 999: 0.99 } },
  { id: 'goldSilverCentral', name: 'GoldSilver Central', cat: 'digital', type: 'physical', pop: 13, en: 'Online bullion marketplace', bm: 'Pasaran jongkong emas dalam talian', url: 'https://goldsilvercentral.com.sg', buy: { 999: 1.04, 916: 1.08 }, sell: { 999: 0.99, 916: 0.97 } },
  { id: 'mygold', name: 'MyGold (Maybank)', cat: 'digital', type: 'digital', pop: 11, en: 'Maybank digital gold', bm: 'Emas digital Maybank', url: 'https://www.maybank2u.com.my', buy: { 999: 1.05 }, sell: { 999: 0.98 } },
  { id: 'maybank', name: 'Maybank Gold Account-i', cat: 'bank', type: 'digital', pop: 4, en: 'Gold savings passbook', bm: 'Buku simpanan emas', url: 'https://www.maybank2u.com.my', buy: { 999: 1.08 }, sell: { 999: 0.97 } },
  { id: 'cimb', name: 'CIMB Gold', cat: 'bank', type: 'digital', pop: 7, en: 'Gold investment account', bm: 'Akaun pelaburan emas', url: 'https://www.cimb.com.my', buy: { 999: 1.08 }, sell: { 999: 0.97 } },
  { id: 'kfh', name: 'KFH Gold Account-i', cat: 'bank', type: 'digital', pop: 12, en: 'Islamic gold savings', bm: 'Simpanan emas Islamik', url: 'https://www.kfh.com.my', buy: { 999: 1.07 }, sell: { 999: 0.97 } },
  { id: 'uob', name: 'UOB Gold Account', cat: 'bank', type: 'digital', pop: 14, en: 'Gold savings account', bm: 'Akaun simpanan emas', url: 'https://www.uob.com.my', buy: { 999: 1.08 }, sell: { 999: 0.97 } },
  { id: 'kedaiEmasAnuar', name: 'Kedai Emas Anuar', cat: 'jeweller', type: 'physical', pop: 9, en: 'Popular gold retail chain', bm: 'Rangkaian kedai emas popular', url: 'https://www.kedaiemasanuar.com.my', buy: { 999: 1.07, 916: 1.10, 750: 1.13 }, sell: { 999: 0.97, 916: 0.96, 750: 0.95 } },
  { id: 'nubex', name: 'Nubex', cat: 'dealer', type: 'physical', pop: 15, en: 'Low-premium bullion supplier', bm: 'Pembekal jongkong premium rendah', url: 'https://www.nubex.com.my', buy: { 999: 1.06, 916: 1.09 }, sell: { 999: 0.98, 916: 0.96 } },
  { id: 'deGem', name: 'DeGem', cat: 'jeweller', type: 'physical', pop: 16, en: 'Premium diamond & gold jeweller', bm: 'Barang kemas berlian & emas premium', url: 'https://www.degem.com', buy: { 999: 1.11, 916: 1.15, 750: 1.18 }, sell: { 999: 0.96, 916: 0.95, 750: 0.94 } },
  { id: 'msgold', name: 'MSGold', cat: 'dealer', type: 'physical', pop: 17, en: 'Online gold bar dealer', bm: 'Peniaga jongkong emas dalam talian', url: 'https://msgold.my', buy: { 999: 1.07, 916: 1.10 }, sell: { 999: 0.97, 916: 0.96 } },
  { id: 'selberan', name: 'Selberan', cat: 'jeweller', type: 'physical', pop: 18, en: 'Fine jewellery house since 1972', bm: 'Pengeluar barang kemas halus sejak 1972', url: 'https://www.selberan.com', buy: { 999: 1.11, 916: 1.15, 750: 1.18 }, sell: { 999: 0.96, 916: 0.95, 750: 0.94 } },
];

const events = [
  { date: '2026-06-09', en: 'US CPI Data Release', bm: 'Data CPI AS Dikeluarkan', type: 'up' },
  { date: '2026-06-04', en: 'ECB Rate Decision', bm: 'Keputusan Kadar ECB', type: 'down' },
  { date: '2026-05-28', en: 'FOMC Meeting Minutes', bm: 'Minit Mesyuarat FOMC', type: 'neutral' },
  { date: '2026-05-20', en: 'US-China Trade Talks', bm: 'Rundingan Dagang AS-China', type: 'up' },
  { date: '2026-05-14', en: 'Fed Rate Hold 4.5%', bm: 'Fed Kekal Kadar 4.5%', type: 'up' },
  { date: '2026-05-01', en: 'US Jobs Report Miss', bm: 'Laporan Kerja AS Lemah', type: 'up' },
  { date: '2026-04-15', en: 'Middle East Ceasefire', bm: 'Gencatan Senjata Timur Tengah', type: 'down' },
  { date: '2026-04-02', en: 'Q1 GDP Contracts', bm: 'KDNK S1 Menguncup', type: 'up' },
  { date: '2026-03-18', en: 'Fed Rate Cut 25bps', bm: 'Fed Potong Kadar 25bps', type: 'up' },
  { date: '2026-02-25', en: 'Ukraine Peace Deal', bm: 'Perjanjian Damai Ukraine', type: 'down' },
  { date: '2026-01-20', en: 'Global Bank Stress', bm: 'Tekanan Bank Global', type: 'up' },
  { date: '2025-12-15', en: 'Year-End Rally', bm: 'Kenaikan Akhir Tahun', type: 'up' },
];

const faq = [
  { q: { en: 'How is the gold price in Malaysia calculated?', bm: 'Bagaimana harga emas di Malaysia dikira?' }, a: { en: 'Malaysian gold prices start from the international spot price, quoted in US dollars per troy ounce (31.1035g). This is converted to Ringgit using the live USD/MYR exchange rate, then divided into a per-gram price. Dealers add a premium of roughly 3–18% on top of spot to cover minting, distribution and profit — that is why retail prices are always higher than the spot price shown in our Compare tab.', bm: 'Harga emas Malaysia bermula daripada harga spot antarabangsa, disebut dalam dolar AS per auns troy (31.1035g). Ia ditukar kepada Ringgit menggunakan kadar USD/MYR semasa, kemudian dibahagikan kepada harga per gram. Peniaga menambah premium kira-kira 3–18% di atas spot untuk kos tempaan, pengedaran dan keuntungan — sebab itulah harga runcit sentiasa lebih tinggi daripada harga spot dalam tab Banding kami.' } },
  { q: { en: 'What is the difference between 999, 916 and 750 gold?', bm: 'Apakah beza emas 999, 916 dan 750?' }, a: { en: 'The number refers to purity in parts per thousand. 999 (24K) is 99.9% pure gold, used for investment bars and coins. 916 (22K) is 91.6% pure and is the standard for Malaysian jewellery because it is more durable. 750 (18K) is 75% gold mixed with other metals. Investment buyers usually choose 999 because you pay less for craftsmanship and it is easier to resell at a fair price.', bm: 'Nombor tersebut merujuk kepada ketulenan dalam per seribu. 999 (24K) ialah 99.9% emas tulen, digunakan untuk jongkong dan syiling pelaburan. 916 (22K) ialah 91.6% tulen dan menjadi piawaian barang kemas Malaysia kerana lebih tahan lasak. 750 (18K) ialah 75% emas bercampur logam lain. Pelabur biasanya memilih 999 kerana kurang membayar upah pertukangan dan lebih mudah dijual semula pada harga berpatutan.' } },
  { q: { en: 'Should I buy physical or digital gold?', bm: 'Patut beli emas fizikal atau digital?' }, a: { en: 'Physical gold (bars, coins, jewellery) is yours to hold with no counterparty risk, but you must store it safely and spreads are wider. Digital gold (bank gold accounts and apps) lets you start from as little as RM10 with instant buy/sell and tighter spreads, but you rely on the provider’s credibility and most accounts are unallocated. Many Malaysians mix both: digital for monthly saving, physical for long-term wealth. Use the Physical/Digital filter in our Compare tab to see which is which.', bm: 'Emas fizikal (jongkong, syiling, barang kemas) adalah milik anda sepenuhnya tanpa risiko pihak ketiga, tetapi perlu disimpan dengan selamat dan spread lebih luas. Emas digital (akaun emas bank dan aplikasi) membolehkan anda bermula serendah RM10 dengan jual beli segera dan spread lebih ketat, tetapi anda bergantung pada kredibiliti penyedia dan kebanyakan akaun tidak diperuntukkan. Ramai rakyat Malaysia menggabungkan kedua-duanya: digital untuk simpanan bulanan, fizikal untuk kekayaan jangka panjang. Guna penapis Fizikal/Digital dalam tab Banding kami.' } },
  { q: { en: 'What is the spread and why does it matter?', bm: 'Apakah spread dan kenapa ia penting?' }, a: { en: 'The spread is the gap between a dealer’s selling price and their buy-back price, shown as a percentage on each card in our Compare tab. If you buy at RM600/g and the dealer buys back at RM540/g, the spread is 10% — gold must rise 10% before you break even. A lower spread means you recover your cost faster, so compare spreads, not just the sticker price.', bm: 'Spread ialah jurang antara harga jualan peniaga dengan harga belian balik mereka, dipaparkan sebagai peratusan pada setiap kad dalam tab Banding kami. Jika anda beli pada RM600/g dan peniaga beli balik pada RM540/g, spread ialah 10% — emas mesti naik 10% sebelum anda pulang modal. Spread lebih rendah bermakna anda pulih kos lebih cepat, jadi bandingkan spread, bukan sekadar harga jualan.' } },
  { q: { en: 'When is a good time to buy gold?', bm: 'Bilakah masa terbaik untuk membeli emas?' }, a: { en: 'Nobody can time the market perfectly, but two approaches work well. Dollar-cost averaging — buying a fixed amount every month — smooths out price swings. Buying dips: our Signal indicator flags when the price falls below its recent average with an oversold RSI, historically a better entry point. Long-term holders worry less about timing: gold in ringgit has risen substantially over the past decade as a hedge against inflation and currency weakness.', bm: 'Tiada siapa boleh menjangka pasaran dengan tepat, tetapi dua pendekatan terbukti berkesan. Purata kos ringgit — membeli jumlah tetap setiap bulan — meratakan turun naik harga. Membeli ketika harga jatuh: penunjuk Isyarat kami menanda apabila harga jatuh bawah purata terkini dengan RSI terlebih jual, secara sejarah titik masuk yang lebih baik. Pemegang jangka panjang kurang risau tentang masa: emas dalam ringgit telah naik dengan ketara sedekad lalu sebagai lindung nilai inflasi dan kelemahan mata wang.' } },
  { q: { en: 'How is zakat on gold calculated in Malaysia?', bm: 'Bagaimana zakat emas dikira di Malaysia?' }, a: { en: 'Zakat is due when your gold holdings exceed the nisab (85g of pure gold) and have been held for one full year (haul). The rate is 2.5% of current market value. Gold jewellery that is regularly worn is exempt up to the uruf limit (commonly 800–850g depending on state). Use our Zakat Calculator in the Tools tab — it can autofill from your portfolio and links directly to official zakat bodies for online payment.', bm: 'Zakat wajib apabila pegangan emas anda melebihi nisab (85g emas tulen) dan telah disimpan genap setahun (haul). Kadarnya 2.5% daripada nilai pasaran semasa. Barang kemas emas yang kerap dipakai dikecualikan sehingga had uruf (biasanya 800–850g bergantung negeri). Guna Kalkulator Zakat kami dalam tab Alat — ia boleh mengisi automatik daripada portfolio anda dan berpaut terus ke badan zakat rasmi untuk bayaran dalam talian.' } },
  { q: { en: 'Is gold a good investment in Malaysia?', bm: 'Adakah emas pelaburan yang baik di Malaysia?' }, a: { en: 'Gold is primarily a store of value, not an income asset — it pays no dividends but protects against inflation and ringgit depreciation. Because gold trades in US dollars, a weaker ringgit lifts the local price even when the world price is flat. Many advisers suggest holding 5–15% of a portfolio in gold for diversification. This is general information, not financial advice.', bm: 'Emas adalah penyimpan nilai, bukan aset pendapatan — ia tidak membayar dividen tetapi melindungi daripada inflasi dan kejatuhan ringgit. Oleh kerana emas didagangkan dalam dolar AS, ringgit yang lemah menaikkan harga tempatan walaupun harga dunia mendatar. Ramai penasihat mencadangkan 5–15% portfolio dalam emas untuk kepelbagaian. Ini maklumat umum, bukan nasihat kewangan.' } },
  { q: { en: 'How do I store physical gold safely?', bm: 'Bagaimana menyimpan emas fizikal dengan selamat?' }, a: { en: 'Common options: a home safe (fast access, but arrange insurance), a bank safe deposit box (roughly RM100–400 per year), or dealer vault storage offered by companies like Public Gold. Keep purchase receipts and certificates — they matter greatly at resale. Never store large amounts unsecured at home.', bm: 'Pilihan biasa: peti besi di rumah (akses pantas, tetapi uruskan insurans), peti simpanan selamat bank (kira-kira RM100–400 setahun), atau simpanan bilik kebal peniaga seperti Public Gold. Simpan resit pembelian dan sijil — ia sangat penting semasa jualan semula. Jangan sesekali simpan jumlah besar tanpa keselamatan di rumah.' } },
  { q: { en: 'How do I sell gold at the best price?', bm: 'Bagaimana menjual emas pada harga terbaik?' }, a: { en: 'Compare buy-back prices first — the Cheapest sort and Best Sell badge in our Compare tab show who pays the most today. Selling back to the dealer you bought from is usually smoothest; bring the original certificate and receipt. Jewellery loses the workmanship fee (upah) at resale, so bars and coins retain value better. Avoid panic-selling during dips; our Signal can help you spot overbought peaks instead.', bm: 'Bandingkan harga belian balik dahulu — susunan Termurah dan lencana Jual Terbaik dalam tab Banding kami menunjukkan siapa membayar paling tinggi hari ini. Menjual semula kepada peniaga asal biasanya paling lancar; bawa sijil dan resit asal. Barang kemas kehilangan upah pertukangan semasa jualan semula, jadi jongkong dan syiling lebih mengekalkan nilai. Elakkan jual panik ketika harga jatuh; Isyarat kami boleh membantu mengesan puncak terlebih beli.' } },
  { q: { en: 'What makes gold prices move?', bm: 'Apakah yang menggerakkan harga emas?' }, a: { en: 'The big drivers are US interest rates (higher rates make gold less attractive versus bonds), inflation data, the strength of the US dollar, central-bank buying, and geopolitical crises that trigger safe-haven demand. For Malaysians the USD/MYR rate adds a second layer — a weaker ringgit raises local prices. Our chart marks major market events so you can see these effects across history.', bm: 'Pemacu utama ialah kadar faedah AS (kadar tinggi menjadikan emas kurang menarik berbanding bon), data inflasi, kekuatan dolar AS, pembelian bank pusat, dan krisis geopolitik yang mencetuskan permintaan aset selamat. Bagi rakyat Malaysia, kadar USD/MYR menambah lapisan kedua — ringgit lemah menaikkan harga tempatan. Carta kami menanda peristiwa pasaran utama supaya anda boleh melihat kesan ini sepanjang sejarah.' } },
];

module.exports = { dealers, events, faq };
